language: node_js

sudo: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install tesseract-ocr tesseract-ocr-eng tesseract-ocr-hun

install:
  - npm ci

# keep the npm cache around to speed up installs
cache:
  directories:
    - "$HOME/.npm"

node_js:
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
